<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="Victor Johnson">
<title>Predicting MLB Team Wins Using Statistical Modeling</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="MLBWins_files/libs/clipboard/clipboard.min.js"></script>
<script src="MLBWins_files/libs/quarto-html/quarto.js"></script>
<script src="MLBWins_files/libs/quarto-html/popper.min.js"></script>
<script src="MLBWins_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="MLBWins_files/libs/quarto-html/anchor.min.js"></script>
<link href="MLBWins_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="MLBWins_files/libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="MLBWins_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="MLBWins_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="MLBWins_files/libs/bootstrap/bootstrap-1bc8a17f135ab3d594c857e9f48e611b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light"><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
</head>
<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a></li>
  <li>
<a href="#data-exploration" id="toc-data-exploration" class="nav-link" data-scroll-target="#data-exploration"><span class="header-section-number">2</span> Data Exploration</a>
  <ul class="collapse">
<li><a href="#summary-and-descriptive-statistics" id="toc-summary-and-descriptive-statistics" class="nav-link" data-scroll-target="#summary-and-descriptive-statistics"><span class="header-section-number">2.1</span> Summary and Descriptive Statistics</a></li>
  <li>
<a href="#visualizations-of-data" id="toc-visualizations-of-data" class="nav-link" data-scroll-target="#visualizations-of-data"><span class="header-section-number">2.2</span> Visualizations of Data</a>
  <ul class="collapse">
<li><a href="#distribution-and-correlation-of-the-variables" id="toc-distribution-and-correlation-of-the-variables" class="nav-link" data-scroll-target="#distribution-and-correlation-of-the-variables"><span class="header-section-number">2.2.1</span> Distribution and Correlation of the Variables</a></li>
  <li><a href="#missing-data" id="toc-missing-data" class="nav-link" data-scroll-target="#missing-data"><span class="header-section-number">2.2.2</span> Missing Data</a></li>
  </ul>
</li>
  </ul>
</li>
  <li>
<a href="#data-preparation" id="toc-data-preparation" class="nav-link" data-scroll-target="#data-preparation"><span class="header-section-number">3</span> Data Preparation</a>
  <ul class="collapse">
<li><a href="#dealing-with-missing-variables" id="toc-dealing-with-missing-variables" class="nav-link" data-scroll-target="#dealing-with-missing-variables"><span class="header-section-number">3.1</span> Dealing with missing variables</a></li>
  <li><a href="#using-buckets" id="toc-using-buckets" class="nav-link" data-scroll-target="#using-buckets"><span class="header-section-number">3.2</span> Using Buckets</a></li>
  <li>
<a href="#additional-variables-and-transformations" id="toc-additional-variables-and-transformations" class="nav-link" data-scroll-target="#additional-variables-and-transformations"><span class="header-section-number">3.3</span> Additional Variables and Transformations</a>
  <ul class="collapse">
<li><a href="#additional-variable-ops" id="toc-additional-variable-ops" class="nav-link" data-scroll-target="#additional-variable-ops"><span class="header-section-number">3.3.1</span> Additional Variable: OPS</a></li>
  <li><a href="#dealing-with-skewness" id="toc-dealing-with-skewness" class="nav-link" data-scroll-target="#dealing-with-skewness"><span class="header-section-number">3.3.2</span> Dealing with Skewness</a></li>
  </ul>
</li>
  <li><a href="#final-summary-statistics-table" id="toc-final-summary-statistics-table" class="nav-link" data-scroll-target="#final-summary-statistics-table"><span class="header-section-number">3.4</span> Final Summary Statistics Table</a></li>
  </ul>
</li>
  <li>
<a href="#building-models" id="toc-building-models" class="nav-link" data-scroll-target="#building-models"><span class="header-section-number">4</span> Building Models</a>
  <ul class="collapse">
<li><a href="#model-1" id="toc-model-1" class="nav-link" data-scroll-target="#model-1"><span class="header-section-number">4.1</span> Model 1</a></li>
  <li><a href="#model-2" id="toc-model-2" class="nav-link" data-scroll-target="#model-2"><span class="header-section-number">4.2</span> Model 2</a></li>
  <li><a href="#model-3" id="toc-model-3" class="nav-link" data-scroll-target="#model-3"><span class="header-section-number">4.3</span> Model 3</a></li>
  <li><a href="#model-4" id="toc-model-4" class="nav-link" data-scroll-target="#model-4"><span class="header-section-number">4.4</span> Model 4</a></li>
  </ul>
</li>
  <li>
<a href="#model-selection" id="toc-model-selection" class="nav-link" data-scroll-target="#model-selection"><span class="header-section-number">5</span> Model Selection</a>
  <ul class="collapse">
<li><a href="#multicollinearity-check" id="toc-multicollinearity-check" class="nav-link" data-scroll-target="#multicollinearity-check"><span class="header-section-number">5.1</span> Multicollinearity check</a></li>
  <li><a href="#model-3-alteration" id="toc-model-3-alteration" class="nav-link" data-scroll-target="#model-3-alteration"><span class="header-section-number">5.2</span> Model 3 Alteration</a></li>
  <li><a href="#residual-visualizations" id="toc-residual-visualizations" class="nav-link" data-scroll-target="#residual-visualizations"><span class="header-section-number">5.3</span> Residual Visualizations</a></li>
  <li><a href="#predictions" id="toc-predictions" class="nav-link" data-scroll-target="#predictions"><span class="header-section-number">5.4</span> Predictions</a></li>
  </ul>
</li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="header-section-number">6</span> Conclusion</a></li>
  </ul></nav>
</div>
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title">Predicting MLB Team Wins Using Statistical Modeling</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Victor Johnson </p>
          </div>
  </div>
    
  
    
  </div>
  


</header><div style="page-break-after: always;"></div>
<section id="introduction" class="level1" data-number="1"><h1 data-number="1">
<span class="header-section-number">1</span> Introduction</h1>
<p>This report analyzes team-data from Major League Baseball (MLB) spanning from 1871-2006 to identify key variables that impact wins. Using the training data set, I clean and transform several variables, create new metrics such as OPS (on-base plus slugging percentage), and address missing/skewed data. Finally, I perform several regressions and choose the one that best predicts a professional baseball team’s total wins for a season.</p>
</section><section id="data-exploration" class="level1" data-number="2"><h1 data-number="2">
<span class="header-section-number">2</span> Data Exploration</h1>
<section id="summary-and-descriptive-statistics" class="level2" data-number="2.1"><h2 data-number="2.1" class="anchored" data-anchor-id="summary-and-descriptive-statistics">
<span class="header-section-number">2.1</span> Summary and Descriptive Statistics</h2>
<p>Here are summary statistics for the training data set.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Summary Statistics
=======================================================
Statistic          N     Mean    St. Dev.   Min   Max  
-------------------------------------------------------
TARGET_WINS      2,276  80.791    15.752     0    146  
TEAM_BATTING_H   2,276 1,469.270  144.591   891  2,554 
TEAM_BATTING_2B  2,276  241.247   46.801    69    458  
TEAM_BATTING_3B  2,276  55.250    27.939     0    223  
TEAM_BATTING_HR  2,276  99.612    60.547     0    264  
TEAM_BATTING_BB  2,276  501.559   122.671    0    878  
TEAM_BATTING_SO  2,174  735.605   248.526    0   1,399 
TEAM_BASERUN_SB  2,145  124.762   87.791     0    697  
TEAM_BASERUN_CS  1,504  52.804    22.956     0    201  
TEAM_BATTING_HBP  191   59.356    12.967    29     95  
TEAM_PITCHING_H  2,276 1,779.210 1,406.843 1,137 30,132
TEAM_PITCHING_HR 2,276  105.699   61.299     0    343  
TEAM_PITCHING_BB 2,276  553.008   166.357    0   3,645 
TEAM_PITCHING_SO 2,174  817.730   553.085    0   19,278
TEAM_FIELDING_E  2,276  246.481   227.771   65   1,898 
TEAM_FIELDING_DP 1,990  146.388   26.226    52    228  
-------------------------------------------------------</code></pre>
</div>
</div>
<p><strong>What these summary statistics show</strong></p>
<p>There are 16 variables describing a professional baseball team’s offensive and defensive statistics. These include batting statistics such as TEAM_BATTING_HR for home runs, pitching statistics, like TEAM_PITCHING_SO for strikeouts, and fielding statistics like TEAM_FIELDING_E for errors. The data covers about 2,200 records that represent a professional baseball team from 1871 to 2006 inclusive.</p>
<p>We can also already see that some variables have missing data. For example, HPB only has 191 observations. This will be useful to keep in mind later when addressing missing data.</p>
<p><strong>Categorically, the variables fit into these groups:</strong></p>
<ul>
<li><p><strong>Batting</strong>: hits (H), doubles (2B), triples (3B), home runs (HR), walks (BB), strikeouts (SO) and hit by pitches (HBP).</p></li>
<li><p><strong>Base running</strong>: steals (SB), and caught stealing (CS)</p></li>
<li><p><strong>Pitching</strong>: hits given up (H), home runs given up (HR) walks given up (BB), and strikeouts (SO).</p></li>
<li>
<p><strong>Fielding</strong>: errors committed (E), and double plays turned (DP).</p>
<p>The final key variable is <strong>TARGET_WINS</strong>, representing the number of wins each team achieved in that season. Interesting to note is the minimum wins in a season is 0 (seems unlikely) and the maximum is 146 (exceptionally high, never actually done in MLB). So we will keep an eye on the legitimacy of the data and the predictability of the models later on.</p>
</li>
</ul>
<p>Next we will look at some visualizations of the data to get a better understanding of its distribution, correlation and if any data is missing.</p>
</section><section id="visualizations-of-data" class="level2" data-number="2.2"><h2 data-number="2.2" class="anchored" data-anchor-id="visualizations-of-data">
<span class="header-section-number">2.2</span> Visualizations of Data</h2>
<section id="distribution-and-correlation-of-the-variables" class="level3" data-number="2.2.1"><h3 data-number="2.2.1" class="anchored" data-anchor-id="distribution-and-correlation-of-the-variables">
<span class="header-section-number">2.2.1</span> Distribution and Correlation of the Variables</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="MLBWins_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="MLBWins_files/figure-html/unnamed-chunk-4-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The first visualization shows a relatively normal (bell curve) distribution of team wins compared to the number of teams. The average is around 80 to 81 wins per team.</p>
<p>The second visualization shows the variables positively correlated with wins from the batting perspective are hits, home runs, doubles, and hit by pitches. From the pitching side, hits given up, walks given up, and home runs given up are positively correlated.</p>
</section><section id="missing-data" class="level3" data-number="2.2.2"><h3 data-number="2.2.2" class="anchored" data-anchor-id="missing-data">
<span class="header-section-number">2.2.2</span> Missing Data</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="MLBWins_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This last visualization shows that there is some missing data in this data set.</p>
<p>This graph shows that there are 6 variables that are missing information. Hit by pitches have the highest percentage of missing data, at around 92%. This means that roughly 92% of team-seasons don’t have a hit by pitch number, so only about 8% of the rows actually contain a usable HBP value.</p>
<div style="page-break-after: always;"></div>
</section></section></section><section id="data-preparation" class="level1" data-number="3"><h1 data-number="3">
<span class="header-section-number">3</span> Data Preparation</h1>
<section id="dealing-with-missing-variables" class="level2" data-number="3.1"><h2 data-number="3.1" class="anchored" data-anchor-id="dealing-with-missing-variables">
<span class="header-section-number">3.1</span> Dealing with missing variables</h2>
<p>Because HBP is missing over 90% of observations, I decided to drop the variable entirely. There is too much missing data to try to accurately impute numbers for HBP, and it doesn’t appear to be a highly explanatory variable for wins anyway based on the correlation chart. For the second most missing variable, TEAM_BASERUNNING_CS or caught stealing, I decided to impute the numbers since roughly 40% is missing. Caught stealing data is also informative for predicting wins since getting caught stealing leads to an out and takes a runner out of scoring possibility.</p>
<p>However before imputing, lets look at the distribution of the variable.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="MLBWins_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>I imputed using the median, since it is less sensitive to outliers than imputing using the mean. While any imputation is not perfect, median is the best way to impute (without over complication). Since caught stealing is Missing at Random (MAR) because it was not recorded early on, using median preserves the central tendency of the distribution without introducing strong assumptions.</p>
<p>Before imputing, I also flag the missing variables (all not just HPB and CS) to use later on.</p>
<p>The following graph shows the distribution <strong>after</strong> the imputation.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="MLBWins_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The large spike at 50 is due to the missing data being replaced by the median (~50). Although this clearly makes the data less robust, when performing regression analysis the missing values are flagged so we can distinguish between actual and imputed data and decide which model yields the best results.</p>
</section><section id="using-buckets" class="level2" data-number="3.2"><h2 data-number="3.2" class="anchored" data-anchor-id="using-buckets">
<span class="header-section-number">3.2</span> Using Buckets</h2>
<p>I decided to create win-range buckets to more easily describe success levels for teams, and to see how certain variables are more or less prevalent with successful vs unsuccessful teams.</p>
<p><strong>Win Buckets</strong></p>
<ul>
<li><p><strong>0-70 wins</strong>, unsuccessful teams, lost more games than they won.</p></li>
<li><p><strong>70-79 wins</strong>, less than .500 (even record) so still unsuccessful</p></li>
<li><p><strong>80-89 wins</strong> , successful teams most above .500</p></li>
<li><p><strong>90-99 wins</strong>, very successful teams, likely made playoffs</p></li>
<li><p><strong>&gt;100 wins</strong>, exceptional teams, almost guaranteed to have made playoffs</p></li>
</ul>
<p>These buckets are useful for a multitude of reasons. For example, we should expect based on theory that teams with more home runs are in the higher win buckets. We can see in this visual that almost no teams with less than 70 wins had more than 150 home runs (purple). We also see that many of the successful teams (89-100+ wins) had over 100 home runs.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="MLBWins_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Only a small share of team-seasons achieved more than 100 wins, so counts in that category are limited. The bars in the 100+ win range therefore represent rare, exceptional teams</p>
</section><section id="additional-variables-and-transformations" class="level2" data-number="3.3"><h2 data-number="3.3" class="anchored" data-anchor-id="additional-variables-and-transformations">
<span class="header-section-number">3.3</span> Additional Variables and Transformations</h2>
<section id="additional-variable-ops" class="level3" data-number="3.3.1"><h3 data-number="3.3.1" class="anchored" data-anchor-id="additional-variable-ops">
<span class="header-section-number">3.3.1</span> Additional Variable: OPS</h3>
<p>I also decided to create an additional variable for team on base plus slugging percentage (OPS). This statistic is often used in Major League Baseball so I thought it would be valuable to include to help predict total wins. While on base percentage and slugging percentage is not available in the data set, but I can calculate a rough estimate using the variables we do have.</p>
<p>I did this by calculating the number of singles and then total bases. Then a proxy estimate for at bats, by adding hits plus strikeouts. This is not a perfect measure since at bats also includes outs besides strikeouts. These out metrics are not available in the dataset, so OPS is inflated a bit than real OPS statistics. Still, it is a useful metric since it weighs home runs and doubles more heavily than singles (due to slugging percentage). Slugging percentage was calculated by dividing total bases (1×singles + 2×doubles + 3×triples + 4×home runs) by proxy_AB (hits + strikeouts).</p>
<div class="cell">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">df_train</span> <span class="op">&lt;-</span> <span class="va">df_train</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">mutate</span><span class="op">(</span></span>
<span>    <span class="co"># rough calculation of total bases:</span></span>
<span>    <span class="co"># 1*singles + 2*doubles + 3*triples + 4*home runs</span></span>
<span>    </span>
<span>    singles <span class="op">=</span> <span class="va">TEAM_BATTING_H</span> <span class="op">-</span> <span class="op">(</span><span class="va">TEAM_BATTING_2B</span> <span class="op">+</span></span>
<span>                                <span class="va">TEAM_BATTING_3B</span> <span class="op">+</span></span>
<span>                                <span class="va">TEAM_BATTING_HR</span><span class="op">)</span>,</span>
<span></span>
<span>    total_bases <span class="op">=</span> <span class="va">singles</span> <span class="op">+</span> <span class="fl">2</span><span class="op">*</span><span class="va">TEAM_BATTING_2B</span> <span class="op">+</span></span>
<span>                  <span class="fl">3</span><span class="op">*</span><span class="va">TEAM_BATTING_3B</span> <span class="op">+</span> <span class="fl">4</span><span class="op">*</span><span class="va">TEAM_BATTING_HR</span>,</span>
<span></span>
<span>    <span class="co"># proxy at-bats (walks are not at-bats)</span></span>
<span>    proxy_AB <span class="op">=</span> <span class="va">TEAM_BATTING_H</span> <span class="op">+</span> <span class="va">TEAM_BATTING_SO</span>,</span>
<span></span>
<span>    <span class="co"># approximate OBP (hits + walks over AB + walks)</span></span>
<span>    OBP_proxy <span class="op">=</span> <span class="op">(</span><span class="va">TEAM_BATTING_H</span> <span class="op">+</span> <span class="va">TEAM_BATTING_BB</span><span class="op">)</span> <span class="op">/</span></span>
<span>                <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">pmax</a></span><span class="op">(</span><span class="va">proxy_AB</span> <span class="op">+</span> <span class="va">TEAM_BATTING_BB</span>, <span class="fl">1</span><span class="op">)</span>,</span>
<span></span>
<span>    <span class="co"># approximate SLG</span></span>
<span>    SLG_proxy <span class="op">=</span> <span class="va">total_bases</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">pmax</a></span><span class="op">(</span><span class="va">proxy_AB</span>, <span class="fl">1</span><span class="op">)</span>,</span>
<span></span>
<span>    <span class="co"># OPS-like metric</span></span>
<span>    OPS_proxy <span class="op">=</span> <span class="va">OBP_proxy</span> <span class="op">+</span> <span class="va">SLG_proxy</span></span>
<span>  <span class="op">)</span></span>
<span></span>
<span><span class="co"># Graph to show that OPS_proxy relates to team wins</span></span>
<span><span class="fu">ggplot</span><span class="op">(</span><span class="va">df_train</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">OPS_proxy</span>, y <span class="op">=</span> <span class="va">TARGET_WINS</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_point</span><span class="op">(</span>alpha <span class="op">=</span> <span class="fl">0.4</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_smooth</span><span class="op">(</span>method <span class="op">=</span> <span class="st">"lm"</span>, se <span class="op">=</span> <span class="cn">FALSE</span>, color <span class="op">=</span> <span class="st">"steelblue"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span>title <span class="op">=</span> <span class="st">"Relationship of OPS Metric to Team Wins"</span>,</span>
<span>       x <span class="op">=</span> <span class="st">"OPS (proxy)"</span>, y <span class="op">=</span> <span class="st">"Wins"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="MLBWins_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This visualization shows that the new OPS variable is positively correlated with wins. The higher OPS teams had more wins on average.</p>
</section><section id="dealing-with-skewness" class="level3" data-number="3.3.2"><h3 data-number="3.3.2" class="anchored" data-anchor-id="dealing-with-skewness">
<span class="header-section-number">3.3.2</span> Dealing with Skewness</h3>
<p>Before going into building models, I also want to test to see if any variables display skewness. If they do, I would mathematically transform them to make them more useful for interpretation.</p>
<div class="cell">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">skewness</span><span class="op">(</span><span class="va">df_train</span><span class="op">$</span><span class="va">TEAM_PITCHING_SO</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 22.17455</code></pre>
</div>
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">skewness</span><span class="op">(</span><span class="va">df_train</span><span class="op">$</span><span class="va">TEAM_PITCHING_H</span>,  na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 10.32951</code></pre>
</div>
</div>
<p>These numbers show that strikeouts and hits (from the pitching perspective) are skewed to the right. This means strikeouts and hits are heavily concentrated at lower values and contain some large outliers, which effects the distribution. To account for this, I transform the two variables using log1p to compress the right tail.</p>
<div class="cell">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">#Transform the two pitching variables to reduce skewness</span></span>
<span><span class="co">#log1p takes the natural log of (1 +x) to smooth out data</span></span>
<span><span class="va">df_train</span> <span class="op">&lt;-</span> <span class="va">df_train</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">mutate</span><span class="op">(</span></span>
<span>    log1p_TEAM_PITCHING_SO <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">log1p</a></span><span class="op">(</span><span class="va">TEAM_PITCHING_SO</span><span class="op">)</span>,</span>
<span>    log1p_TEAM_PITCHING_H  <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">log1p</a></span><span class="op">(</span><span class="va">TEAM_PITCHING_H</span><span class="op">)</span></span>
<span>  <span class="op">)</span></span>
<span><span class="fu">psych</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/psych/man/describe.html">describe</a></span><span class="op">(</span><span class="va">df_train</span><span class="op">$</span><span class="va">log1p_TEAM_PITCHING_SO</span><span class="op">)</span><span class="op">$</span><span class="va">skew</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -7.044934</code></pre>
</div>
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">psych</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/psych/man/describe.html">describe</a></span><span class="op">(</span><span class="va">df_train</span><span class="op">$</span><span class="va">log1p_TEAM_PITCHING_H</span><span class="op">)</span><span class="op">$</span><span class="va">skew</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4.299764</code></pre>
</div>
</div>
<p>After transforming the variables, the skew is far less than leaving them as default.</p>
</section></section><section id="final-summary-statistics-table" class="level2" data-number="3.4"><h2 data-number="3.4" class="anchored" data-anchor-id="final-summary-statistics-table">
<span class="header-section-number">3.4</span> Final Summary Statistics Table</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Summary Statistics: Final Regression Variables
=========================================================
Statistic                N     Mean   St. Dev. Min   Max 
---------------------------------------------------------
TARGET_WINS            2,276  80.79    15.75    0    146 
TEAM_BATTING_H         2,276 1,469.27  144.59  891  2,554
TEAM_BATTING_HR        2,276  99.61    60.55    0    264 
TEAM_BATTING_BB        2,276  501.56   122.67   0    878 
TEAM_BATTING_2B        2,276  241.25   46.80    69   458 
TEAM_BATTING_3B        2,276  55.25    27.94    0    223 
OPS_proxy              2,174   1.70     0.16   1.21 2.30 
log1p_TEAM_PITCHING_SO 2,174   6.59     0.72   0.00 9.87 
log1p_TEAM_PITCHING_H  2,276   7.40     0.31   7.04 10.31
TEAM_FIELDING_E        2,276  246.48   227.77   65  1,898
TEAM_FIELDING_DP       1,990  146.39   26.23    52   228 
TEAM_BASERUN_SB        2,145  124.76   87.79    0    697 
TEAM_BASERUN_CS        2,276  51.51    18.75    0    201 
---------------------------------------------------------</code></pre>
</div>
</div>
<div style="page-break-after: always;"></div>
<p>This final summary statistics includes 12 explanatory variables and one dependent variable (target wins). I included the OPS metric I created as well as the two transformed variables. Beyond this I include hits, home runs, walks, doubles, triples, fielding errors, double plays, stolen bases and caught stealing (after median imputation). I will not use all 12 variables in each model, but this table shows what I am pulling from for the models.</p>
</section></section><section id="building-models" class="level1" data-number="4"><h1 data-number="4">
<span class="header-section-number">4</span> Building Models</h1>
<section id="model-1" class="level2" data-number="4.1"><h2 data-number="4.1" class="anchored" data-anchor-id="model-1">
<span class="header-section-number">4.1</span> Model 1</h2>
<p>The first model is the simplest, just using the core offensive numbers to see how useful they are at predicting wins. The independent variables are TEAM_BATTING_H (hits), TEAM_BATTING_HR (home runs), and TEAM_BATTING_BB (walks). This model only focuses on the offense to see how the offensive metrics are predictive of team wins.</p>
<p><strong>Estimating Equation</strong></p>
<p><span class="math display">\[
\mathit{WINS}_i = \beta_0 + \beta_1 H_i + \beta_2 HR_i + \beta_3 BB_i + \varepsilon_i\]</span></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Regression Results: Model One
===============================================
                        Dependent variable:    
                    ---------------------------
                            TARGET_WINS        
-----------------------------------------------
TEAM_BATTING_H               0.044***          
                              (0.002)          
TEAM_BATTING_HR              0.016***          
                              (0.006)          
TEAM_BATTING_BB              0.030***          
                              (0.003)          
Constant                      -0.623           
                              (3.304)          
-----------------------------------------------
Observations                   2,276           
R2                             0.222           
Adjusted R2                    0.221           
Residual Std. Error     13.902 (df = 2272)     
F Statistic          216.270*** (df = 3; 2272) 
===============================================
Note:               *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
</div>
</div>
<p><strong>Coefficients</strong></p>
<p>The coefficients for all three independent variables are positive, which makes sense based on theory. We should expect hits, home runs, and walks to positively relate to wins. Specifically, each hit is associated with roughly 0.044 more wins in a season, while each home run leads to 0.015 more wins and walks leading to 0.029 more wins.</p>
<p><strong>Significance</strong></p>
<p>Both hits and walks are statistically significant at all three traditional thresholds, 10%, 5% and 1%. However, the adjusted R squared is low at 0.2211. Only roughly 22% of the variation in wins is explained by batting hits, home runs, and walks. While this is a decent model to start, there are likely better models with the variables we have available.</p>
</section><section id="model-2" class="level2" data-number="4.2"><h2 data-number="4.2" class="anchored" data-anchor-id="model-2">
<span class="header-section-number">4.2</span> Model 2</h2>
<p>The second model uses the two transformed pitching variables, strike outs and hits given up to see how pitching can impact games won. I also included errors, to examine how important defense is to winning games. Therefore the variables used are log1p_TEAM_PITCHING_SO (the transformed strike outs variable), log1p_TEAM_PITCHING_H (the transformed hits given up variable) and TEAM_FIELDING_E (errors).</p>
<p><strong>Estimating Equation</strong></p>
<p><span class="math display">\[
\mathit{Wins}_i=\beta_0+\beta_1\mathit{log1p\_PitchingSO}_i+\beta_2\mathit{log1p\_PitchingH}_i+\beta_3\mathit{FieldingE_i}
\]</span></p>
<div style="page-break-after: always;"></div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Regression Results: Model Two
==================================================
                           Dependent variable:    
                       ---------------------------
                               TARGET_WINS        
--------------------------------------------------
log1p_TEAM_PITCHING_SO          -1.813***         
                                 (0.494)          
log1p_TEAM_PITCHING_H           19.295***         
                                 (1.795)          
TEAM_FIELDING_E                 -0.035***         
                                 (0.002)          
Constant                       -41.597***         
                                (13.369)          
--------------------------------------------------
Observations                      2,174           
R2                                0.086           
Adjusted R2                       0.085           
Residual Std. Error        14.896 (df = 2170)     
F Statistic             68.420*** (df = 3; 2170)  
==================================================
Note:                  *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
</div>
</div>
<p><strong>Coefficients</strong></p>
<p>While the three explanatory variables at statistically significant at 1%, the coefficients sign is not consistent with what we should expect based on theory. We should expect more strike outs to lead to more wins (positive coefficient). Similarly we should expect hits to have a negative coefficient since giving up more hits should not lead to additional wins. The sign of the coefficient on errors is consistent with theory though, since more errors should lead to less wins (negative sign).</p>
<p><strong>Significance</strong></p>
<p>As mentioned the three variables are statistically significant. However, there is again concern with an even lower adjusted R square measure at 0.085. Only 8.5% of the variation in wins is because of these variables. This makes this model not very powerful, and not usable for analysis.</p>
<p>Despite the low adjusted R squared, Model 2 is still valuable for comparison and completeness. It isolates pitching and defensive performance, allowing us to see how much team success can be explained by run prevention alone. Showing that these variables account for only about 8.5 % of win variation highlights the relative importance of offense and underscores that pitching and defense, while statistically significant, play a more limited role in this data set than batting.</p>
</section><section id="model-3" class="level2" data-number="4.3"><h2 data-number="4.3" class="anchored" data-anchor-id="model-3">
<span class="header-section-number">4.3</span> Model 3</h2>
<p>The third model combines offensive, defensive and pitching variables to create a complete model. It includes the proxy OPS variable I created, but no other offensive variables due to risk of multicollinearity. For pitching it includes the two transformed variables hits and strike outs again. For fielding, I included fielding errors and double plays. Finally I included both base running metrics, stolen bases and caught stealing.</p>
<p><strong>Estimating Equation</strong></p>
<p><span class="math display">\[
\begin{aligned}\mathit{Wins}_i &amp;= \beta_0 + \beta_1 \mathit{OPS}_i  + \beta_2 \mathit{log1p\_PitchingSO}_i  + \beta_3 \mathit{log1p\_PitchingH}_i \\ &amp;\quad + \beta_4 \mathit{FieldingE}_i  + \beta_5 \mathit{FieldingDP}_i  + \beta_6 \mathit{SB}_i  + \beta_7 \mathit{CS}_i  + \varepsilon_i\end{aligned}\
\]</span></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Regression Results: Model Three
==================================================
                           Dependent variable:    
                       ---------------------------
                               TARGET_WINS        
--------------------------------------------------
OPS_proxy                       92.001***         
                                 (5.719)          
log1p_TEAM_PITCHING_SO          19.520***         
                                 (2.530)          
log1p_TEAM_PITCHING_H          -16.936***         
                                 (4.024)          
TEAM_FIELDING_E                 -0.096***         
                                 (0.007)          
TEAM_FIELDING_DP                -0.102***         
                                 (0.013)          
TEAM_BASERUN_SB                 0.093***          
                                 (0.006)          
TEAM_BASERUN_CS                 -0.045***         
                                 (0.014)          
Constant                       -56.059***         
                                (21.332)          
--------------------------------------------------
Observations                      1,835           
R2                                0.339           
Adjusted R2                       0.336           
Residual Std. Error        10.721 (df = 1827)     
F Statistic             133.692*** (df = 7; 1827) 
==================================================
Note:                  *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
</div>
</div>
<p><strong>Coefficients</strong></p>
<p>The signs of OPS, errors, stolen bases and caught stealing are consistent with the theory. OPS should be positively related to wins, errors should be negatively related, stolen bases should be positive, and caught stealing should be negative.</p>
<p>However, some signs are unexpected. For example, double plays should have a positive coefficient based on theory, more double plays turned should lead to additional wins. Also, similar to model 2, the two pitching variables have unexpected signs. This likely reflects the structure of the data set: modern teams play longer seasons and therefore accumulate more strikeouts and hits while also recording more wins. The unexpected signs is likely to due how baseball has evolved over 100 years. I decided to keep the pitching metrics in the model anyway, because they help capture the variation in wins and are statistically significant.</p>
<p><strong>Significance</strong></p>
<p>All seven variables are statistically significant at the highest 1% threshold. Including more variables has also increased the adjusted R squared to 0.339, meaning roughly 33.9% of the variation in total wins can be explained using these variables.</p>
</section><section id="model-4" class="level2" data-number="4.4"><h2 data-number="4.4" class="anchored" data-anchor-id="model-4">
<span class="header-section-number">4.4</span> Model 4</h2>
<p>For fun, I decided to create a fourth model with even more variables to see how R squared would be affected. While its important to note simply adding variables does not improve the accuracy of the model, model 4’s purpose is to show how the regression would look by omitting OPS and including the bulk of the offensive, defensive, and pitching variables.</p>
<p><strong>Estimating Equation</strong></p>
<p><span class="math display">\[ \begin{aligned}\mathit{WINS}_i &amp;= \beta_0   + \beta_1 H_i  + \beta_2 HR_i  + \beta_3 BB_i  + \beta_4 2B_i  + \beta_5 3B_i \\ &amp;\quad + \beta_6 SB_i  + \beta_7 \mathit{log1p\_PitchingSO}_i  + \beta_8 \mathit{log1p\_PitchingH}_i \\ &amp;\quad + \beta_9 E_i  + \beta_{10} DP_i  + \varepsilon_i\end{aligned} \]</span></p>
<div style="page-break-after: always;"></div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Regression Results: Model Four
==================================================
                           Dependent variable:    
                       ---------------------------
                               TARGET_WINS        
--------------------------------------------------
TEAM_BATTING_H                  0.021***          
                                 (0.006)          
TEAM_BATTING_HR                 0.096***          
                                 (0.009)          
TEAM_BATTING_BB                 0.035***          
                                 (0.003)          
TEAM_BATTING_2B                 -0.057***         
                                 (0.009)          
TEAM_BATTING_3B                 0.177***          
                                 (0.019)          
TEAM_BASERUN_SB                 0.070***          
                                 (0.006)          
log1p_TEAM_PITCHING_SO         -15.224***         
                                 (1.749)          
log1p_TEAM_PITCHING_H           14.324***         
                                 (3.770)          
TEAM_FIELDING_E                 -0.111***         
                                 (0.007)          
TEAM_FIELDING_DP                -0.113***         
                                 (0.012)          
Constant                        50.497**          
                                (23.140)          
--------------------------------------------------
Observations                      1,835           
R2                                0.392           
Adjusted R2                       0.389           
Residual Std. Error        10.285 (df = 1824)     
F Statistic            117.763*** (df = 10; 1824) 
==================================================
Note:                  *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
</div>
</div>
<p><strong>Coefficients</strong></p>
<p>The signs remain the roughly the same as the previous model, with some expected signs (hits, home runs, walks, triples, stolen bases) and some unexpected (doubles, hits given up). It is interesting to note that pitching strike outs now has the expected positive sign, however it is no longer statistically significant at the traditional three thresholds.</p>
<p><strong>Significance</strong></p>
<p>As mentioned above, pitching strikeouts is no longer statistically significant, nor is batting hits. The purpose of the model was to obtain a higher adjusted R squared, which is does successfully now reaching 0.598 or nearly 60% of the variation in wins predicted.</p>
</section></section><section id="model-selection" class="level1" data-number="5"><h1 data-number="5">
<span class="header-section-number">5</span> Model Selection</h1>
<section id="multicollinearity-check" class="level2" data-number="5.1"><h2 data-number="5.1" class="anchored" data-anchor-id="multicollinearity-check">
<span class="header-section-number">5.1</span> Multicollinearity check</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>    Model               Variable      VIF
1 Model 3              OPS_proxy 9.636386
2 Model 3 log1p_TEAM_PITCHING_SO 8.309211
3 Model 4         TEAM_BATTING_H 6.313450</code></pre>
</div>
</div>
</section><section id="model-3-alteration" class="level2" data-number="5.2"><h2 data-number="5.2" class="anchored" data-anchor-id="model-3-alteration">
<span class="header-section-number">5.2</span> Model 3 Alteration</h2>
<p>After checking for multicollinearity issues in the model, I’ve decided to slightly alter model three by dropping pitching strike outs from the model. While this will reduce the amount of information the model uses, the VIF analysis showed that pitching strikeouts were highly collinear with OPS, which can inflate standard errors and distort coefficient estimates. Additionally since the expected sign of pitching strikeouts was incorrect anyway, this proves to be worthwhile variable to drop in the end.</p>
<p><strong>Updated Estimating Equation</strong></p>
<p><span class="math display">\[
\begin{aligned}\mathit{WINS}_i &amp;= \beta_0   + \beta_1 \mathit{OPS}_i  + \beta_2 \mathit{log1p\_PitchingH}_i \\  &amp;\quad + \beta_3 \mathit{FieldingE}_i  + \beta_4 \mathit{FieldingDP}_i  + \beta_5 SB_i  + \beta_6 CS_i  + \varepsilon_i\end{aligned}
\]</span></p>
<div style="page-break-after: always;"></div>
<p><strong>Updated Regression Results</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Regression Results: Updated Model Three
=================================================
                          Dependent variable:    
                      ---------------------------
                              TARGET_WINS        
-------------------------------------------------
OPS_proxy                      53.082***         
                                (2.740)          
log1p_TEAM_PITCHING_H            2.988           
                                (3.136)          
TEAM_FIELDING_E                -0.127***         
                                (0.006)          
TEAM_FIELDING_DP               -0.098***         
                                (0.013)          
TEAM_BASERUN_SB                0.095***          
                                (0.006)          
TEAM_BASERUN_CS                -0.074***         
                                (0.014)          
Constant                        -0.751           
                               (20.411)          
-------------------------------------------------
Observations                     1,835           
R2                               0.317           
Adjusted R2                      0.315           
Residual Std. Error       10.891 (df = 1828)     
F Statistic            141.518*** (df = 6; 1828) 
=================================================
Note:                 *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
</div>
</div>
<p><strong>Updated VIF test</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>            OPS_proxy log1p_TEAM_PITCHING_H       TEAM_FIELDING_E 
             2.142669              1.756311              1.586693 
     TEAM_FIELDING_DP       TEAM_BASERUN_SB       TEAM_BASERUN_CS 
             1.338734              1.746811              1.324863 </code></pre>
</div>
</div>
<p>The VIF test for the updated model 3 shows there are no longer multicollinearity concerns.</p>
<p>After this refinement, I’ve selected the <strong>updated model 3</strong> as the best model.</p>
<p><strong>Model 1</strong> (offense only) explained about 22% of the variation in wins, but ignored pitching and defense.</p>
<p><strong>Model 2</strong> (pitching and defense only) explained less than 9% of variation, and while coefficients were statistically significant, many had counterintuitive signs, reflecting historical era effects.</p>
<p><strong>Model 4</strong> achieved the highest adjusted R squared at nearly 60%, but at the cost of including many overlapping offensive variables, creating multicollinearity and reducing interpretability.</p>
<p><strong>The original model 3</strong> had issues with multicollinearity and interpretation issues with the unexpected sign for pitching strike outs.</p>
<p><strong>Finally, the updated model 3</strong> has the best balance of pitching, hitting, and defensive metrics while eliminating the previous multicollinearity concerns. While the adjusted R squared might be lower than other models, this sacrifice is worthwhile because of its strong interpretative value and lack of multicollinearity.</p>
</section><section id="residual-visualizations" class="level2" data-number="5.3"><h2 data-number="5.3" class="anchored" data-anchor-id="residual-visualizations">
<span class="header-section-number">5.3</span> Residual Visualizations</h2>
<p><strong>Residuals vs Fitted Values for the Updated Model 3</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="MLBWins_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This shows there are no clear patterns, and relatively even spread without many extreme outliers. This makes this model strong for predicting total team wins.</p>
<p>The F-statistic for the updated model 3 is large at 141.5, so the variation explained by the model is larger than the unexplained variation.</p>
</section><section id="predictions" class="level2" data-number="5.4"><h2 data-number="5.4" class="anchored" data-anchor-id="predictions">
<span class="header-section-number">5.4</span> Predictions</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   INDEX Predicted_WINS
1      9       61.00004
2     10       65.92624
3     14       71.33988
4     47       88.35380
5     60       25.92111
6     63       35.99005
7     74       86.28454
8     83       72.29145
9     98       76.54846
10   120       78.77855</code></pre>
</div>
</div>
<p>This shows that based on my updated model three, these teams are expected to win this many games based on their offensive, defensive and pitching metrics used in the updated model 3. To keep the report simple, only 10 teams are represented here.</p>
</section></section><section id="conclusion" class="level1" data-number="6"><h1 data-number="6">
<span class="header-section-number">6</span> Conclusion</h1>
<p>Overall, the analysis shows that team performance can be reasonably predicted from a combination of batting, pitching, defensive, and base running statistics. While the model is not perfect, and baseball can be an unpredictable game with luck and randomness playing a part in winning games, it is still valuable. With more data and additional refinements, the predictions could be improved further, but even in its current form the project highlights the power of econometric modeling in sports analysis.</p>
</section></main><!-- /main column --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>